Loss function (GIOU loss) implimented
ImTheSquid/CodeCheck pull request #9
Opened 2024-10-14 17:24 UTC by Ban-Ironic-Ohms

2024-10-14 17:25 UTC, Ban-Ironic-Ohms commented
@ImTheSquid Take a look?

2024-10-14 19:05 UTC, ImTheSquid requested changes

2024-10-14 19:05 UTC, ImTheSquid commented on neural/src/giou_tensor.rs
This file probably shouldn't be here. Is there a reason you want to include it?

2024-10-14 23:22 UTC, Ban-Ironic-Ohms commented
Your right - those were old code files. Entire directory removed as all functionality is captured in the neural dir.

2024-10-15 18:58 UTC, ImTheSquid requested changes
Remove all of the lang-translate'd files as well as the java dataset; they blow up the size of the repository and should be stored separately anyways. Also remove neural/src/giou_tensor.rs or tell me why it's needed.

2024-10-15 19:06 UTC, Ban-Ironic-Ohms commented
Removed - the lang-translate code itself could still be useful, but we can just go back to rev history and get it if needed

2024-10-15 21:18 UTC, ImTheSquid commented
Add back the script you used but not the code that you used the script on

2024-10-15 23:38 UTC, Ban-Ironic-Ohms commented
Done

2024-10-16 14:42 UTC, ImTheSquid approved these changes

2024-10-16 14:42 UTC, merged